import Kwon1002.GaussEstimates
import Erdos1002.GaussCylinderContraction
import Erdos1002.GaussPrefixCylinderPartition

/-!
# L33 scratch: Lemma 3.3 (shrinking anti-concentration)
-/

open MeasureTheory Set
open scoped ENNReal

namespace Kwon1002

noncomputable section

/-! ## The backward continuant ratio `Y_j = q_{j-1}/q_j` -/

/-- `Y_j = q_{j-1}/q_j`, with the convention `q_{-1} = 0` so that `Y_0 = 0`. -/
def Yfun (α : ℝ) : ℕ → ℝ
  | 0 => 0
  | (j + 1) => (denom α j : ℝ) / (denom α (j + 1) : ℝ)

/-- The **reversed** digit word `[a_j, a_{j-1}, …, a_1]`. -/
def revWord (α : ℝ) : ℕ → List ℕ
  | 0 => []
  | (j + 1) => digit α j :: revWord α j

lemma revWord_length (α : ℝ) (j : ℕ) : (revWord α j).length = j := by
  induction j with
  | zero => rfl
  | succ j ih => simp [revWord, ih]

lemma revWord_pos {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1) (hirr : Irrational α) (j : ℕ) :
    ∀ q ∈ revWord α j, 0 < q := by
  induction j with
  | zero => simp [revWord]
  | succ j ih =>
      intro q hq
      simp only [revWord, List.mem_cons] at hq
      rcases hq with h | h
      · exact h ▸ one_le_digit hα hirr j
      · exact ih q h

lemma denomPair_pos_AC {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1) (hirr : Irrational α) :
    ∀ j : ℕ, 0 < denom α j ∧ 0 < denom α (j + 1) := by
  intro j
  induction j with
  | zero =>
      refine ⟨by norm_num [denom], ?_⟩
      have h : denom α 1 = digit α 0 := rfl
      rw [h]; exact one_le_digit hα hirr 0
  | succ j ih =>
      refine ⟨ih.2, ?_⟩
      have h : denom α (j + 1 + 1)
          = digit α (j + 1) * denom α (j + 1) + denom α j := rfl
      rw [h]
      exact lt_of_lt_of_le ih.1 (Nat.le_add_left _ _)

lemma denom_pos_AC {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1) (hirr : Irrational α) (j : ℕ) :
    0 < denom α j := (denomPair_pos_AC hα hirr j).1

/-- `Y_{j+1} = 1/(a_{j+1} + Y_j)`: the backward ratio is generated by the very
same inverse Gauss branches, read in reverse order. -/
lemma Yfun_succ {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1) (hirr : Irrational α) (j : ℕ) :
    Yfun α (j + 1) = Erdos1002.gaussInverseBranch (digit α j) (Yfun α j) := by
  cases j with
  | zero =>
      have h0 : denom α 0 = 1 := rfl
      have h1 : denom α 1 = digit α 0 := rfl
      simp [Yfun, Erdos1002.gaussInverseBranch, h0, h1]
  | succ j =>
      have h : denom α (j + 1 + 1)
          = digit α (j + 1) * denom α (j + 1) + denom α j := rfl
      have hA : (0 : ℝ) < (denom α (j + 1) : ℝ) := by
        exact_mod_cast denom_pos_AC hα hirr (j + 1)
      have hC : (0 : ℝ) < (denom α (j + 1 + 1) : ℝ) := by
        exact_mod_cast denom_pos_AC hα hirr (j + 1 + 1)
      rw [h] at hC
      push_cast at hC
      simp only [Yfun, Erdos1002.gaussInverseBranch, h, Nat.cast_add, Nat.cast_mul]
      have hrw : (digit α (j + 1) : ℝ) + (denom α j : ℝ) / (denom α (j + 1) : ℝ)
          = ((digit α (j + 1) : ℝ) * (denom α (j + 1) : ℝ) + (denom α j : ℝ))
              / (denom α (j + 1) : ℝ) := by
        field_simp
      rw [hrw, one_div_div]

lemma Yfun_eq_gaussInverseWord {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1)
    (hirr : Irrational α) (j : ℕ) :
    Yfun α j = Erdos1002.gaussInverseWord (revWord α j) 0 := by
  induction j with
  | zero => simp [Yfun, revWord, Erdos1002.gaussInverseWord]
  | succ j ih =>
      rw [Yfun_succ hα hirr j, ih]
      simp [revWord, Erdos1002.gaussInverseWord]

lemma gaussInverseWord_append_singleton (u : List ℕ) (q : ℕ) (x : ℝ) :
    Erdos1002.gaussInverseWord (u ++ [q]) x
      = Erdos1002.gaussInverseWord u (Erdos1002.gaussInverseBranch q x) := by
  induction u with
  | nil => simp [Erdos1002.gaussInverseWord]
  | cons p u ih => simp [Erdos1002.gaussInverseWord, ih]

/-- `α` is recovered from its first `j` digits and `T^j α`. -/
lemma gaussInverseWord_gaussIter {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1)
    (hirr : Irrational α) (j : ℕ) :
    Erdos1002.gaussInverseWord (revWord α j).reverse (gaussIter α j) = α := by
  induction j with
  | zero => simp [revWord, Erdos1002.gaussInverseWord]
  | succ j ih =>
      have hstep : Erdos1002.gaussInverseBranch (digit α j) (gaussIter α (j + 1))
          = gaussIter α j := by
        have h := inv_gaussIter_eq hα hirr j
        rw [Erdos1002.gaussInverseBranch, ← h, one_div, inv_inv]
      have hrev : (revWord α (j + 1)).reverse
          = (revWord α j).reverse ++ [digit α j] := by
        simp [revWord]
      rw [hrev, gaussInverseWord_append_singleton, hstep, ih]

/-- Every irrational of `(0,1)` lies in the closed depth-`j` cylinder of its own
digit word. -/
lemma mem_closedGaussPrefixCylinder {α : ℝ} (hα : α ∈ Ioo (0 : ℝ) 1)
    (hirr : Irrational α) (j : ℕ) :
    α ∈ Erdos1002.closedGaussPrefixCylinder (revWord α j).reverse := by
  refine ⟨gaussIter α j, ?_, gaussInverseWord_gaussIter hα hirr j⟩
  have h := gaussIter_mem_Ioo hα hirr j
  exact ⟨h.1.le, h.2.le⟩

private lemma volume_unit_slice_ne_top (P : ℝ → Prop) :
    volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧ P α} ≠ ⊤ := by
  refine ne_top_of_le_ne_top ?_ (measure_mono (fun x hx => hx.1))
  simp [Real.volume_Ioo]

/-! ## The anti-concentration input -/

/-- Depth-`n` digit words whose **reversed** endpoint `[0;a_n,…,a_1]` lies in the
`δ`-window around `t`.  This is the index set of the exceptional event: it is a
union of *complete* depth-`n` cylinders, exactly as the manuscript insists. -/
private def goodWords (t δ : ℝ) (n : ℕ) : Set (List ℕ) :=
  {w | w.length = n ∧ (∀ q ∈ w, 0 < q) ∧
    |Erdos1002.gaussInverseWord w.reverse 0 - t| < δ}

/-- The reversed cylinder of a good word sits inside the `δ`-window around `t`,
fattened by the uniform cylinder diameter `4^{-⌊n/2⌋}`. -/
private lemma halfOpen_subset_window {t δ : ℝ} {n : ℕ} {w : List ℕ}
    (hw : w ∈ goodWords t δ n) :
    Erdos1002.gaussHalfOpenPrefixCylinder w.reverse
      ⊆ Icc (t - δ - (1 / 4 : ℝ) ^ (n / 2)) (t + δ + (1 / 4 : ℝ) ^ (n / 2)) := by
  obtain ⟨hlen, hpos, hnear⟩ := hw
  have hposr : ∀ q ∈ w.reverse, 0 < q := fun q hq => hpos q (List.mem_reverse.mp hq)
  intro x hx
  have hxc : x ∈ Erdos1002.closedGaussPrefixCylinder w.reverse :=
    Erdos1002.gaussHalfOpenPrefixCylinder_subset_closed hposr hx
  have he0 : Erdos1002.gaussInverseWord w.reverse 0
      ∈ Erdos1002.closedGaussPrefixCylinder w.reverse := ⟨0, by norm_num, rfl⟩
  have hdist := Erdos1002.dist_le_of_mem_closedGaussPrefixCylinder hposr hxc he0
  rw [Real.dist_eq] at hdist
  have hlenr : w.reverse.length = n := by rw [List.length_reverse]; exact hlen
  rw [hlenr] at hdist
  obtain ⟨h1, h2⟩ := abs_le.mp hdist
  obtain ⟨h3, h4⟩ := abs_lt.mp hnear
  exact ⟨by linarith, by linarith⟩

/-! ## Möbius normal form of an inverse word, and the mirror identity -/

/-- `quad w = (A,B,C,D)` with `gaussInverseWord w x = (A x + B)/(C x + D)`.
This is the matrix `E_{a_1} ⋯ E_{a_n}`, `E_a = !![0,1;1,a]`, written out. -/
def quad : List ℕ → ℤ × ℤ × ℤ × ℤ
  | [] => (1, 0, 0, 1)
  | q :: w => ((quad w).2.2.1, (quad w).2.2.2,
      (q : ℤ) * (quad w).2.2.1 + (quad w).1,
      (q : ℤ) * (quad w).2.2.2 + (quad w).2.1)

def qA (w : List ℕ) : ℤ := (quad w).1
def qB (w : List ℕ) : ℤ := (quad w).2.1
def qC (w : List ℕ) : ℤ := (quad w).2.2.1
def qD (w : List ℕ) : ℤ := (quad w).2.2.2

@[simp] lemma qA_nil : qA [] = 1 := rfl
@[simp] lemma qB_nil : qB [] = 0 := rfl
@[simp] lemma qC_nil : qC [] = 0 := rfl
@[simp] lemma qD_nil : qD [] = 1 := rfl
@[simp] lemma qA_cons (q : ℕ) (w : List ℕ) : qA (q :: w) = qC w := rfl
@[simp] lemma qB_cons (q : ℕ) (w : List ℕ) : qB (q :: w) = qD w := rfl
@[simp] lemma qC_cons (q : ℕ) (w : List ℕ) : qC (q :: w) = (q : ℤ) * qC w + qA w := rfl
@[simp] lemma qD_cons (q : ℕ) (w : List ℕ) : qD (q :: w) = (q : ℤ) * qD w + qB w := rfl

lemma quad_bounds {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q) :
    0 ≤ qA w ∧ 0 ≤ qB w ∧ 0 ≤ qC w ∧ 0 < qD w ∧ qB w ≤ qD w := by
  induction w with
  | nil => norm_num
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : ∀ p ∈ w, 0 < p := fun p hp => hpos p (by simp [hp])
      obtain ⟨hA, hB, hC, hD, hBD⟩ := ih htail
      have hq1 : (1 : ℤ) ≤ (q : ℤ) := by exact_mod_cast hq
      refine ⟨by simpa using hC, by simpa using hD.le, ?_, ?_, ?_⟩ <;>
        simp only [qB_cons, qC_cons, qD_cons] <;> nlinarith

lemma quad_det (w : List ℕ) : qA w * qD w - qB w * qC w = (-1) ^ w.length := by
  induction w with
  | nil => norm_num
  | cons q w ih =>
      simp only [qA_cons, qB_cons, qC_cons, qD_cons, List.length_cons, pow_succ]
      rw [← ih]; ring

lemma quad_append_singleton (w : List ℕ) (q : ℕ) :
    qA (w ++ [q]) = qB w ∧ qB (w ++ [q]) = qA w + (q : ℤ) * qB w ∧
      qC (w ++ [q]) = qD w ∧ qD (w ++ [q]) = qC w + (q : ℤ) * qD w := by
  induction w with
  | nil => refine ⟨by simp, by simp, by simp, by simp⟩
  | cons p u ih =>
      obtain ⟨h1, h2, h3, h4⟩ := ih
      rw [List.cons_append]
      refine ⟨?_, ?_, ?_, ?_⟩
      · rw [qA_cons, qB_cons, h3]
      · rw [qB_cons, qA_cons, qB_cons, h4]
      · rw [qC_cons, qD_cons, h3, h1]
      · rw [qD_cons, qC_cons, qD_cons, h4, h2]; ring

/-- **Mirror identity**: reversing a word transposes the matrix, so the
continuant `D = K(a_1,…,a_n)` is palindromic. -/
lemma quad_reverse (w : List ℕ) :
    qA w.reverse = qA w ∧ qB w.reverse = qC w ∧
      qC w.reverse = qB w ∧ qD w.reverse = qD w := by
  induction w with
  | nil => simp
  | cons q u ih =>
      obtain ⟨h1, h2, h3, h4⟩ := ih
      obtain ⟨g1, g2, g3, g4⟩ := quad_append_singleton u.reverse q
      rw [List.reverse_cons]
      refine ⟨?_, ?_, ?_, ?_⟩
      · rw [g1, h2, qA_cons]
      · rw [g2, h1, h2, qC_cons]; ring
      · rw [g3, h4, qB_cons]
      · rw [g4, h3, h4, qD_cons]; ring

lemma gaussInverseWord_eq_quad {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q) {x : ℝ} (hx : 0 ≤ x) :
    Erdos1002.gaussInverseWord w x
      = ((qA w : ℝ) * x + (qB w : ℝ)) / ((qC w : ℝ) * x + (qD w : ℝ)) := by
  induction w with
  | nil => simp [Erdos1002.gaussInverseWord]
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : ∀ p ∈ w, 0 < p := fun p hp => hpos p (by simp [hp])
      obtain ⟨hA, hB, hC, hD, _⟩ := quad_bounds htail
      have hCR : (0 : ℝ) ≤ (qC w : ℝ) := by exact_mod_cast hC
      have hDR : (0 : ℝ) < (qD w : ℝ) := by exact_mod_cast hD
      have hden : (0 : ℝ) < (qC w : ℝ) * x + (qD w : ℝ) := by nlinarith
      have hstep : Erdos1002.gaussInverseWord (q :: w) x
          = Erdos1002.gaussInverseBranch q (Erdos1002.gaussInverseWord w x) := rfl
      rw [hstep, Erdos1002.gaussInverseBranch, ih htail]
      have key : ((q : ℝ) + ((qA w : ℝ) * x + (qB w : ℝ)) / ((qC w : ℝ) * x + (qD w : ℝ)))
          = (((q : ℝ) * (qC w : ℝ) + (qA w : ℝ)) * x
              + ((q : ℝ) * (qD w : ℝ) + (qB w : ℝ))) / ((qC w : ℝ) * x + (qD w : ℝ)) := by
        field_simp; ring
      rw [key, one_div_div, qA_cons, qB_cons, qC_cons, qD_cons]
      push_cast
      ring

lemma abs_gaussInverseWord_sub_quad {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q)
    {x y : ℝ} (hx : 0 ≤ x) (hy : 0 ≤ y) :
    |Erdos1002.gaussInverseWord w x - Erdos1002.gaussInverseWord w y|
      = |x - y| / (((qC w : ℝ) * x + (qD w : ℝ)) * ((qC w : ℝ) * y + (qD w : ℝ))) := by
  obtain ⟨hA, hB, hC, hD, _⟩ := quad_bounds hpos
  have hCR : (0 : ℝ) ≤ (qC w : ℝ) := by exact_mod_cast hC
  have hDR : (0 : ℝ) < (qD w : ℝ) := by exact_mod_cast hD
  have hdx : (0 : ℝ) < (qC w : ℝ) * x + (qD w : ℝ) := by nlinarith
  have hdy : (0 : ℝ) < (qC w : ℝ) * y + (qD w : ℝ) := by nlinarith
  rw [gaussInverseWord_eq_quad hpos hx, gaussInverseWord_eq_quad hpos hy]
  have hnum : ((qA w : ℝ) * x + (qB w : ℝ)) / ((qC w : ℝ) * x + (qD w : ℝ))
      - ((qA w : ℝ) * y + (qB w : ℝ)) / ((qC w : ℝ) * y + (qD w : ℝ))
      = ((qA w : ℝ) * (qD w : ℝ) - (qB w : ℝ) * (qC w : ℝ)) * (x - y)
          / (((qC w : ℝ) * x + (qD w : ℝ)) * ((qC w : ℝ) * y + (qD w : ℝ))) := by
    field_simp; ring
  have hdet : |((qA w : ℝ) * (qD w : ℝ) - (qB w : ℝ) * (qC w : ℝ))| = 1 := by
    have h := quad_det w
    have hcast : ((qA w : ℝ) * (qD w : ℝ) - (qB w : ℝ) * (qC w : ℝ))
        = ((((-1 : ℤ)) ^ w.length : ℤ) : ℝ) := by
      rw [← h]; push_cast; ring
    rw [hcast]
    push_cast
    simp [abs_pow]
  rw [hnum, abs_div, abs_mul,
    abs_of_pos (mul_pos hdx hdy), hdet, one_mul]

/-! ## Cylinder measures -/

lemma continuousOn_gaussInverseWord {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q) :
    ContinuousOn (Erdos1002.gaussInverseWord w) (Icc (0 : ℝ) 1) := by
  induction w with
  | nil => simpa [Erdos1002.gaussInverseWord] using continuousOn_id (s := Icc (0 : ℝ) 1)
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : ∀ p ∈ w, 0 < p := fun p hp => hpos p (by simp [hp])
      have hmaps : MapsTo (Erdos1002.gaussInverseWord w) (Icc (0 : ℝ) 1) (Icc (0 : ℝ) 1) :=
        fun x hx => Erdos1002.gaussInverseWord_mem_Icc htail hx
      exact (Erdos1002.continuousOn_gaussInverseBranch q hq).comp (ih htail) hmaps

lemma image_Ioo_subset_halfOpen {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q) :
    Erdos1002.gaussInverseWord w '' Ioo (0 : ℝ) 1
      ⊆ Erdos1002.gaussHalfOpenPrefixCylinder w := by
  induction w with
  | nil =>
      rintro z ⟨y, hy, rfl⟩
      exact ⟨hy.1.le, hy.2⟩
  | cons q w ih =>
      have hq : 0 < q := hpos q (by simp)
      have htail : ∀ p ∈ w, 0 < p := fun p hp => hpos p (by simp [hp])
      rintro z ⟨y, hy, rfl⟩
      have hzy : Erdos1002.gaussInverseWord w y ∈ Ioo (0 : ℝ) 1 :=
        Erdos1002.gaussInverseWord_mem_Ioo htail hy
      have hIco : Erdos1002.gaussInverseWord w y ∈ Ico (0 : ℝ) 1 := ⟨hzy.1.le, hzy.2⟩
      refine ⟨Erdos1002.gaussInverseBranch_mem_firstDigitCylinder hIco q hq, ?_⟩
      show Erdos1002.gaussMap
          (Erdos1002.gaussInverseBranch q (Erdos1002.gaussInverseWord w y))
        ∈ Erdos1002.gaussHalfOpenPrefixCylinder w
      rw [Erdos1002.gaussMap_gaussInverseBranch hIco q hq]
      exact ih htail ⟨y, hy, rfl⟩

lemma ofReal_gap_le_volume_halfOpen {v : List ℕ} (hpos : ∀ q ∈ v, 0 < q) :
    ENNReal.ofReal |Erdos1002.gaussInverseWord v (1 / 4)
        - Erdos1002.gaussInverseWord v (3 / 4)|
      ≤ volume (Erdos1002.gaussHalfOpenPrefixCylinder v) := by
  have hconn : IsPreconnected (Erdos1002.gaussInverseWord v '' Ioo (0 : ℝ) 1) :=
    isPreconnected_Ioo.image _
      ((continuousOn_gaussInverseWord hpos).mono Ioo_subset_Icc_self)
  have h14 : Erdos1002.gaussInverseWord v (1 / 4)
      ∈ Erdos1002.gaussInverseWord v '' Ioo (0 : ℝ) 1 := ⟨1 / 4, by norm_num, rfl⟩
  have h34 : Erdos1002.gaussInverseWord v (3 / 4)
      ∈ Erdos1002.gaussInverseWord v '' Ioo (0 : ℝ) 1 := ⟨3 / 4, by norm_num, rfl⟩
  have hsub : uIcc (Erdos1002.gaussInverseWord v (1 / 4))
      (Erdos1002.gaussInverseWord v (3 / 4))
      ⊆ Erdos1002.gaussInverseWord v '' Ioo (0 : ℝ) 1 :=
    hconn.ordConnected.uIcc_subset h14 h34
  calc ENNReal.ofReal |Erdos1002.gaussInverseWord v (1 / 4)
          - Erdos1002.gaussInverseWord v (3 / 4)|
      = volume (uIcc (Erdos1002.gaussInverseWord v (1 / 4))
          (Erdos1002.gaussInverseWord v (3 / 4))) := by
        rw [Real.volume_interval, abs_sub_comm]
    _ ≤ volume (Erdos1002.gaussInverseWord v '' Ioo (0 : ℝ) 1) := measure_mono hsub
    _ ≤ volume (Erdos1002.gaussHalfOpenPrefixCylinder v) :=
        measure_mono (image_Ioo_subset_halfOpen hpos)

lemma volume_closedCylinder_le_ofReal {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q) :
    volume (Erdos1002.closedGaussPrefixCylinder w)
      ≤ ENNReal.ofReal (2 / ((qD w : ℝ) * (qD w : ℝ))) := by
  obtain ⟨hA, hB, hC, hD, hBD⟩ := quad_bounds hpos
  have hCR : (0 : ℝ) ≤ (qC w : ℝ) := by exact_mod_cast hC
  have hDR : (0 : ℝ) < (qD w : ℝ) := by exact_mod_cast hD
  have hsub : Erdos1002.closedGaussPrefixCylinder w
      ⊆ Icc (Erdos1002.gaussInverseWord w 0 - 1 / ((qD w : ℝ) * (qD w : ℝ)))
          (Erdos1002.gaussInverseWord w 0 + 1 / ((qD w : ℝ) * (qD w : ℝ))) := by
    rintro z ⟨x, hx, rfl⟩
    have hd := abs_gaussInverseWord_sub_quad hpos hx.1 (le_refl (0 : ℝ))
    rw [sub_zero, abs_of_nonneg hx.1] at hd
    have hdenr : ((qC w : ℝ) * x + (qD w : ℝ)) * ((qC w : ℝ) * 0 + (qD w : ℝ))
        = ((qC w : ℝ) * x + (qD w : ℝ)) * (qD w : ℝ) := by ring
    rw [hdenr] at hd
    have hinner : (0 : ℝ) < (qC w : ℝ) * x + (qD w : ℝ) := by
      nlinarith [mul_nonneg hCR hx.1]
    have hpos1 : (0 : ℝ) < ((qC w : ℝ) * x + (qD w : ℝ)) * (qD w : ℝ) := mul_pos hinner hDR
    have hle : x / (((qC w : ℝ) * x + (qD w : ℝ)) * (qD w : ℝ))
        ≤ 1 / ((qD w : ℝ) * (qD w : ℝ)) := by
      rw [div_le_div_iff₀ hpos1 (by positivity)]
      nlinarith [mul_nonneg (mul_nonneg hCR hx.1) hDR.le,
        mul_nonneg (mul_nonneg hDR.le hDR.le) (sub_nonneg.mpr hx.2)]
    have habs : |Erdos1002.gaussInverseWord w x - Erdos1002.gaussInverseWord w 0|
        ≤ 1 / ((qD w : ℝ) * (qD w : ℝ)) := by rw [hd]; exact hle
    obtain ⟨u1, u2⟩ := abs_le.mp habs
    exact ⟨by linarith, by linarith⟩
  calc volume (Erdos1002.closedGaussPrefixCylinder w)
      ≤ volume (Icc (Erdos1002.gaussInverseWord w 0 - 1 / ((qD w : ℝ) * (qD w : ℝ)))
          (Erdos1002.gaussInverseWord w 0 + 1 / ((qD w : ℝ) * (qD w : ℝ)))) :=
        measure_mono hsub
    _ = ENNReal.ofReal (2 / ((qD w : ℝ) * (qD w : ℝ))) := by
        rw [Real.volume_Icc]; congr 1; ring

/-- **Mirror comparison of cylinder measures.**  The depth-`n` closed cylinder of
`w` and the depth-`n` half-open cylinder of the reversed word `w̄` have comparable
Lebesgue measure, because `K(a_1,…,a_n) = K(a_n,…,a_1)` (`quad_reverse`). -/
theorem volume_closedCylinder_le_volume_halfOpen_reverse
    {w : List ℕ} (hpos : ∀ q ∈ w, 0 < q) :
    volume (Erdos1002.closedGaussPrefixCylinder w)
      ≤ 16 * volume (Erdos1002.gaussHalfOpenPrefixCylinder w.reverse) := by
  have hposr : ∀ q ∈ w.reverse, 0 < q := fun q hq => hpos q (List.mem_reverse.mp hq)
  obtain ⟨hA, hB, hC, hD, hBD⟩ := quad_bounds hpos
  obtain ⟨r1, r2, r3, r4⟩ := quad_reverse w
  have hBR : (0 : ℝ) ≤ (qB w : ℝ) := by exact_mod_cast hB
  have hDR : (0 : ℝ) < (qD w : ℝ) := by exact_mod_cast hD
  have hBDR : (qB w : ℝ) ≤ (qD w : ℝ) := by exact_mod_cast hBD
  have hgap : |Erdos1002.gaussInverseWord w.reverse (1 / 4)
      - Erdos1002.gaussInverseWord w.reverse (3 / 4)|
      = (1 / 2) / (((qB w : ℝ) * (1 / 4) + (qD w : ℝ))
          * ((qB w : ℝ) * (3 / 4) + (qD w : ℝ))) := by
    rw [abs_gaussInverseWord_sub_quad hposr (by norm_num) (by norm_num), r3, r4]
    norm_num
  have hXpos : (0 : ℝ) < ((qB w : ℝ) * (1 / 4) + (qD w : ℝ))
      * ((qB w : ℝ) * (3 / 4) + (qD w : ℝ)) := by nlinarith
  have hnum : 2 / ((qD w : ℝ) * (qD w : ℝ))
      ≤ 16 * |Erdos1002.gaussInverseWord w.reverse (1 / 4)
          - Erdos1002.gaussInverseWord w.reverse (3 / 4)| := by
    rw [hgap, show (16 : ℝ) * ((1 / 2) / (((qB w : ℝ) * (1 / 4) + (qD w : ℝ))
        * ((qB w : ℝ) * (3 / 4) + (qD w : ℝ))))
        = 8 / (((qB w : ℝ) * (1 / 4) + (qD w : ℝ))
            * ((qB w : ℝ) * (3 / 4) + (qD w : ℝ))) from by ring,
      div_le_div_iff₀ (by positivity) hXpos]
    nlinarith [sq_nonneg ((qD w : ℝ) - (qB w : ℝ))]
  calc volume (Erdos1002.closedGaussPrefixCylinder w)
      ≤ ENNReal.ofReal (2 / ((qD w : ℝ) * (qD w : ℝ))) :=
        volume_closedCylinder_le_ofReal hpos
    _ ≤ ENNReal.ofReal (16 * |Erdos1002.gaussInverseWord w.reverse (1 / 4)
          - Erdos1002.gaussInverseWord w.reverse (3 / 4)|) :=
        ENNReal.ofReal_le_ofReal hnum
    _ = 16 * ENNReal.ofReal |Erdos1002.gaussInverseWord w.reverse (1 / 4)
          - Erdos1002.gaussInverseWord w.reverse (3 / 4)| := by
        rw [ENNReal.ofReal_mul (by norm_num)]; norm_num
    _ ≤ 16 * volume (Erdos1002.gaussHalfOpenPrefixCylinder w.reverse) :=
        mul_le_mul_left' (ofReal_gap_le_volume_halfOpen hposr) 16

/-- Anti-concentration for the **backward continuant ratio**
`Y_{k+1} = q_k / q_{k+1} = [0; a_{k+1}, …, a_1]`, written multiplicatively so
that no division (and no positivity side condition on `q_{k+1}`) appears. -/
theorem backward_ratio_anti_concentration :
    ∃ C c : ℝ, 0 < C ∧ 0 < c ∧ ∀ (t : ℝ) (k : ℕ) (δ : ℝ), 0 < δ →
      (volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
          |(denom α k : ℝ) - t * (denom α (k + 1) : ℝ)|
            < δ * (denom α (k + 1) : ℝ)}).toReal
        ≤ C * (δ + Real.exp (-c * ((k : ℝ) + 1))) := by
  refine ⟨64, Real.log 2, by norm_num, Real.log_pos (by norm_num), ?_⟩
  intro t k δ hδ
  have hAc : (goodWords t δ (k + 1)).Countable := Set.to_countable _
  -- Rationals are null.
  have hQnull : volume {x : ℝ | ¬ Irrational x} = 0 := by
    have hset : {x : ℝ | ¬ Irrational x} = Set.range ((↑) : ℚ → ℝ) := by
      ext x; simp [Irrational]
    rw [hset]
    exact (Set.countable_range _).measure_zero _
  -- Step 1: the event is covered by complete depth-`(k+1)` cylinders.
  have hcover : {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
      |(denom α k : ℝ) - t * (denom α (k + 1) : ℝ)| < δ * (denom α (k + 1) : ℝ)}
      ⊆ (⋃ w ∈ goodWords t δ (k + 1), Erdos1002.closedGaussPrefixCylinder w)
        ∪ {x : ℝ | ¬ Irrational x} := by
    rintro α ⟨hα, hineq⟩
    by_cases hirr : Irrational α
    · left
      have hQ : (0 : ℝ) < (denom α (k + 1) : ℝ) := by
        exact_mod_cast denom_pos_AC hα hirr (k + 1)
      have hY : |Yfun α (k + 1) - t| < δ := by
        have hYe : Yfun α (k + 1) = (denom α k : ℝ) / (denom α (k + 1) : ℝ) := rfl
        have key : (denom α k : ℝ) / (denom α (k + 1) : ℝ) - t
            = ((denom α k : ℝ) - t * (denom α (k + 1) : ℝ)) / (denom α (k + 1) : ℝ) := by
          field_simp
        rw [hYe, key, abs_div, abs_of_pos hQ, div_lt_iff₀ hQ]
        exact hineq
      refine Set.mem_biUnion (show (revWord α (k + 1)).reverse ∈ goodWords t δ (k + 1) from ?_)
        (mem_closedGaussPrefixCylinder hα hirr (k + 1))
      refine ⟨by rw [List.length_reverse, revWord_length], ?_, ?_⟩
      · intro q hq
        exact revWord_pos hα hirr (k + 1) q (List.mem_reverse.mp hq)
      · rw [List.reverse_reverse, ← Yfun_eq_gaussInverseWord hα hirr]
        exact hY
    · right; exact hirr
  -- Step 2: countable subadditivity.
  have hstep2 : volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
      |(denom α k : ℝ) - t * (denom α (k + 1) : ℝ)| < δ * (denom α (k + 1) : ℝ)}
      ≤ ∑' w : goodWords t δ (k + 1),
          volume (Erdos1002.closedGaussPrefixCylinder (w : List ℕ)) := by
    calc volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
            |(denom α k : ℝ) - t * (denom α (k + 1) : ℝ)| < δ * (denom α (k + 1) : ℝ)}
        ≤ volume ((⋃ w ∈ goodWords t δ (k + 1), Erdos1002.closedGaussPrefixCylinder w)
            ∪ {x : ℝ | ¬ Irrational x}) := measure_mono hcover
      _ ≤ volume (⋃ w ∈ goodWords t δ (k + 1), Erdos1002.closedGaussPrefixCylinder w)
            + volume {x : ℝ | ¬ Irrational x} := measure_union_le _ _
      _ = volume (⋃ w ∈ goodWords t δ (k + 1), Erdos1002.closedGaussPrefixCylinder w) := by
            rw [hQnull, add_zero]
      _ ≤ ∑' w : goodWords t δ (k + 1),
            volume (Erdos1002.closedGaussPrefixCylinder (w : List ℕ)) := by
            exact measure_biUnion_le _ hAc _
  -- Step 3/4: mirror comparison, term by term.
  have hstep4 : ∑' w : goodWords t δ (k + 1),
        volume (Erdos1002.closedGaussPrefixCylinder (w : List ℕ))
      ≤ ∑' w : goodWords t δ (k + 1),
        16 * volume (Erdos1002.gaussHalfOpenPrefixCylinder (w : List ℕ).reverse) :=
    ENNReal.tsum_le_tsum
      (fun w => volume_closedCylinder_le_volume_halfOpen_reverse w.2.2.1)
  -- Step 5: the mirrored cylinders are pairwise disjoint, so the sum is a measure.
  have hdisj : (goodWords t δ (k + 1)).PairwiseDisjoint
      (fun w : List ℕ => Erdos1002.gaussHalfOpenPrefixCylinder w.reverse) := by
    intro w1 h1 w2 h2 hne
    refine Erdos1002.disjoint_gaussHalfOpenPrefixCylinder_of_sameLength ?_ ?_ ?_ ?_
    · rw [List.length_reverse, List.length_reverse, h1.1, h2.1]
    · intro q hq; exact h1.2.1 q (List.mem_reverse.mp hq)
    · intro q hq; exact h2.2.1 q (List.mem_reverse.mp hq)
    · intro h
      exact hne (by simpa using congrArg List.reverse h)
  have hstep5 : ∑' w : goodWords t δ (k + 1),
        16 * volume (Erdos1002.gaussHalfOpenPrefixCylinder (w : List ℕ).reverse)
      = 16 * volume (⋃ w ∈ goodWords t δ (k + 1),
          Erdos1002.gaussHalfOpenPrefixCylinder (List.reverse w)) := by
    rw [ENNReal.tsum_mul_left]
    congr 1
    exact (measure_biUnion hAc hdisj
      (fun w _ => Erdos1002.measurableSet_gaussHalfOpenPrefixCylinder _)).symm
  -- Step 6: everything sits in one window.
  have hwin : (⋃ w ∈ goodWords t δ (k + 1),
      Erdos1002.gaussHalfOpenPrefixCylinder (List.reverse w))
      ⊆ Icc (t - δ - (1 / 4 : ℝ) ^ ((k + 1) / 2))
          (t + δ + (1 / 4 : ℝ) ^ ((k + 1) / 2)) := by
    refine Set.iUnion₂_subset ?_
    intro w hw
    exact halfOpen_subset_window hw
  have hIcc : volume (Icc (t - δ - (1 / 4 : ℝ) ^ ((k + 1) / 2))
      (t + δ + (1 / 4 : ℝ) ^ ((k + 1) / 2)))
      = ENNReal.ofReal (2 * δ + 2 * (1 / 4 : ℝ) ^ ((k + 1) / 2)) := by
    rw [Real.volume_Icc]; congr 1; ring
  -- Assemble in `ℝ≥0∞`.
  have hchain : volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
      |(denom α k : ℝ) - t * (denom α (k + 1) : ℝ)| < δ * (denom α (k + 1) : ℝ)}
      ≤ 16 * ENNReal.ofReal (2 * δ + 2 * (1 / 4 : ℝ) ^ ((k + 1) / 2)) := by
    refine hstep2.trans (hstep4.trans ?_)
    rw [hstep5, ← hIcc]
    exact mul_le_mul_left' (measure_mono hwin) 16
  -- Back to `ℝ`.
  have htoReal : (volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
      |(denom α k : ℝ) - t * (denom α (k + 1) : ℝ)| < δ * (denom α (k + 1) : ℝ)}).toReal
      ≤ 16 * (2 * δ + 2 * (1 / 4 : ℝ) ^ ((k + 1) / 2)) := by
    have hne : (16 : ℝ≥0∞) * ENNReal.ofReal (2 * δ + 2 * (1 / 4 : ℝ) ^ ((k + 1) / 2)) ≠ ⊤ := by
      simp [ENNReal.mul_eq_top]
    have := ENNReal.toReal_mono hne hchain
    rwa [ENNReal.toReal_mul, ENNReal.toReal_ofReal (by positivity),
      ENNReal.toReal_ofNat] at this
  -- Numerics.
  have hexp : Real.exp (-Real.log 2 * ((k : ℝ) + 1)) = (1 / 2 : ℝ) ^ (k + 1) := by
    rw [← Real.rpow_natCast (1 / 2 : ℝ) (k + 1), Real.rpow_def_of_pos (by norm_num)]
    congr 1
    rw [one_div, Real.log_inv]
    push_cast
    ring
  have hkm : k ≤ 2 * ((k + 1) / 2) := by omega
  have hpow : (1 / 4 : ℝ) ^ ((k + 1) / 2) = (1 / 2 : ℝ) ^ (2 * ((k + 1) / 2)) := by
    rw [pow_mul]; norm_num
  have hmono : (1 / 2 : ℝ) ^ (2 * ((k + 1) / 2)) ≤ (1 / 2 : ℝ) ^ k := by
    exact pow_le_pow_of_le_one (by norm_num) (by norm_num) hkm
  have hhalf : (1 / 2 : ℝ) ^ (k + 1) = (1 / 2 : ℝ) ^ k * (1 / 2) := by
    rw [pow_succ]
  rw [hexp, hhalf]
  rw [hpow] at htoReal
  linarith [htoReal, hmono, hδ]

/-- **Lemma 3.3** (Shrinking anti-concentration). -/
theorem shrinking_anti_concentration :
    ∃ C c : ℝ, 0 < c ∧ ∀ r s : ℤ, (r, s) ≠ (0, 0) → ∀ j : ℕ, 1 ≤ j → ∀ η : ℝ,
      0 < η → η < 1 / 2 →
      (MeasureTheory.volume {α : ℝ | α ∈ Set.Ioo (0 : ℝ) 1 ∧
        |(s : ℝ) * denom α j - (r : ℝ) * denom α (j - 1)| < η * denom α j}).toReal
        ≤ C * (η + Real.exp (-c * j)) := by
  obtain ⟨C, c, hC, hc, hmain⟩ := backward_ratio_anti_concentration
  refine ⟨C, c, hc, ?_⟩
  intro r s hrs j hj η hη hη2
  obtain ⟨k, rfl⟩ : ∃ k, j = k + 1 := ⟨j - 1, by omega⟩
  simp only [Nat.add_sub_cancel]
  have hcast : ((k + 1 : ℕ) : ℝ) = (k : ℝ) + 1 := by push_cast; ring
  by_cases hr : r = 0
  · -- `r = 0`: the event forces `|s| < η < 1/2`, impossible for a nonzero integer.
    subst hr
    have hs : s ≠ 0 := by
      intro h; exact hrs (by simp [h])
    have hempty : {α : ℝ | α ∈ Set.Ioo (0 : ℝ) 1 ∧
        |(s : ℝ) * denom α (k + 1) - ((0 : ℤ) : ℝ) * denom α k|
          < η * denom α (k + 1)} = ∅ := by
      rw [Set.eq_empty_iff_forall_notMem]
      rintro α ⟨-, h⟩
      rw [Int.cast_zero, zero_mul, sub_zero, abs_mul,
        abs_of_nonneg (by positivity : (0 : ℝ) ≤ (denom α (k + 1) : ℝ))] at h
      have hs1 : (1 : ℝ) ≤ |(s : ℝ)| := by
        have : (1 : ℤ) ≤ |s| := Int.one_le_abs (by omega)
        calc (1 : ℝ) = ((1 : ℤ) : ℝ) := by norm_num
          _ ≤ ((|s| : ℤ) : ℝ) := by exact_mod_cast this
          _ = |(s : ℝ)| := by push_cast; ring
      have hQ : (0 : ℝ) ≤ (denom α (k + 1) : ℝ) := by positivity
      nlinarith
    rw [hempty]
    simp only [measure_empty, ENNReal.toReal_zero]
    positivity
  · -- `r ≠ 0`: the event sits inside a `2η`-window for `q_k/q_{k+1}` around `s/r`.
    have hrR : ((r : ℝ)) ≠ 0 := Int.cast_ne_zero.mpr hr
    have hR1 : (1 : ℝ) ≤ |(r : ℝ)| := by
      have : (1 : ℤ) ≤ |r| := Int.one_le_abs (by omega)
      calc (1 : ℝ) = ((1 : ℤ) : ℝ) := by norm_num
        _ ≤ ((|r| : ℤ) : ℝ) := by exact_mod_cast this
        _ = |(r : ℝ)| := by push_cast; ring
    have hsub : {α : ℝ | α ∈ Set.Ioo (0 : ℝ) 1 ∧
        |(s : ℝ) * denom α (k + 1) - (r : ℝ) * denom α k| < η * denom α (k + 1)}
        ⊆ {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
          |(denom α k : ℝ) - ((s : ℝ) / (r : ℝ)) * (denom α (k + 1) : ℝ)|
            < η * (denom α (k + 1) : ℝ)} := by
      rintro α ⟨hα, h⟩
      refine ⟨hα, ?_⟩
      set Q : ℝ := (denom α (k + 1) : ℝ) with hQdef
      set P : ℝ := (denom α k : ℝ) with hPdef
      have hQ : (0 : ℝ) ≤ Q := by rw [hQdef]; positivity
      have hkey : (s : ℝ) * Q - (r : ℝ) * P = -((r : ℝ) * (P - ((s : ℝ) / (r : ℝ)) * Q)) := by
        field_simp; ring
      rw [hkey, abs_neg, abs_mul] at h
      have hX : (0 : ℝ) ≤ |P - ((s : ℝ) / (r : ℝ)) * Q| := abs_nonneg _
      nlinarith
    calc (volume {α : ℝ | α ∈ Set.Ioo (0 : ℝ) 1 ∧
            |(s : ℝ) * denom α (k + 1) - (r : ℝ) * denom α k|
              < η * denom α (k + 1)}).toReal
        ≤ (volume {α : ℝ | α ∈ Ioo (0 : ℝ) 1 ∧
            |(denom α k : ℝ) - ((s : ℝ) / (r : ℝ)) * (denom α (k + 1) : ℝ)|
              < η * (denom α (k + 1) : ℝ)}).toReal :=
          ENNReal.toReal_mono (volume_unit_slice_ne_top _) (measure_mono hsub)
      _ ≤ C * (η + Real.exp (-c * ((k : ℝ) + 1))) := hmain _ _ _ hη
      _ = C * (η + Real.exp (-c * ((k + 1 : ℕ) : ℝ))) := by rw [hcast]

end

end Kwon1002
